name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Replace Firebase Config and Verify ⚙️
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo "Checking if secret is set..."
          if [ -z "$FIREBASE_SECRET" ]; then
            echo "::error::FIREBASE_CONFIG secret is not set or is empty."
            exit 1
          fi
          echo "Secret is present."
          
          # Encode the secret to Base64 to make it shell-safe
          CONFIG_B64=$(echo -n "$FIREBASE_SECRET" | base64 -w 0)
          
          echo "Attempting to replace placeholder with Base64 encoded config..."
          # Replace the placeholder with the Base64 string.
          sed -i "s|\"%%FIREBASE_CONFIG_B64%%\"|\"${CONFIG_B64}\"|g" index.html

          echo "Verifying replacement..."
          if grep -q "%%FIREBASE_CONFIG_B64%%" index.html; then
            echo "::error::Placeholder replacement failed. Please verify the FIREBASE_CONFIG secret format."
            exit 1
          else
            echo "Placeholder was replaced successfully."
          fi

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .

